### PR TITLE
added region parameter for aws provider

### PR DESCRIPTION
**Pull request by riccardo-salamanna**
added region parameter to provider

### CODE REVIEW

**Comment by rs1986x** [comment]
just added region parameter

**Comment by JoshiiSinfield** [comment]
Hi @riccardo-salamanna 

Apologies for late reply. 

The changes you've made will cause the provider blocks to be fully fledged providers and not proxy. 

If you set the provider outside of this module it'll be picked up automatically

**Comment by rs1986x** [comment]
Hey! i'm glad you got back to me - I am not sure i get your answer: do you mean to declare the provider outside of the module as well? It has been a while but i remember having to add the region there... could you give me maybe an example? and again thanks for getting back to me :)

Ricardo

> Hi @riccardo-salamanna
> 
> Apologies for late reply.
> 
> The changes you've made will cause the provider blocks to be fully fledged providers and not proxy.
> 
> If you set the provider outside of this module it'll be picked up automatically

**Comment by robh007** [comment]
I'm closing this as it's no longer valid or correct. You should have defined the region where you declare your provider block then passed this into the module. I've removed the provider block proxy file in this pr #12 as it's now a deprecated pattern. See examples in PR which shows how this can be achieved. Sorry it's taken so long to get back to you.

**Pull request closed without merging**
